### ISSUE TITLE
Post API link if the bot can't see what's wrong with it.

### ISSUE THREAD

**Issue by Querijn** [Querijn/BottyMcBotface#100]
![image](https://user-images.githubusercontent.com/3397066/43033176-ddde7384-8cc5-11e8-92ba-183eebe72254.png)

In this kind of case, it should just post the link and see what happens.

**Comment by Derpthemeus** [comment]
I believe that this should be fixed by #104 once merged

**Comment by Querijn** [comment]
You did this in that PR or is the issue in that image resolved?

**Comment by Derpthemeus** [comment]
In the new PR the bot will always post the URL of each API call, and it also won't ever detect a URL as invalid without identifying why (I think the only reason it did so previously was because it didn't know how to handle query parameters).
