### ISSUE TITLE
API correctness check fails for tournament API calls

### ISSUE THREAD

**Issue by stelar7** [Querijn/BottyMcBotface#110]
Botty doesnt have americas, europe, and asia as valid subdomains for the calls

**Comment by Derpthemeus** [comment]
This is caused by an issue in the OpenAPI definitions that Botty uses. We'll watch https://github.com/MingweiSamuel/riotapi-schema/issues/6 to see if it gets resolved, and can consider implementing a workaround fix if it doesn't.

**Comment by MingweiSamuel** [comment]
americas, europe, and asia have been added, so botty should accept them. This also means botty will accept those platforms on endpoints that don't use them, for now

**Comment by MingweiSamuel** [comment]
Is this fixed?

**Comment by stelar7** [comment]
Yes, it seems to be fixed
