### ISSUE TITLE
Include timezone when outputting gametime

### ISSUE THREAD

**Issue by stelar7** [Querijn/BottyMcBotface#120]
https://github.com/Querijn/BottyMcBotface/blob/0d971837d231532aa11cfd855e441320bc57b9b2/src/ESports.ts#L205-L218

**Comment by Querijn** [comment]
![image](https://user-images.githubusercontent.com/3397066/46944084-748bc900-d071-11e8-8095-08c6e047b445.png)

**Comment by stelar7** [comment]
oh, wrong snippet lol

the Z in https://github.com/Querijn/BottyMcBotface/blob/0d971837d231532aa11cfd855e441320bc57b9b2/src/ESports.ts#L145 means that the timezone info is missing according to the docs

> In addition, the ECMA Script 5 Specification makes an unusual assertion about the offset of ISO 8601 dates:
> The value of an absent time zone offset is "Z"

**Comment by stelar7** [comment]
fixed with 786431e0473cd103f77a63ca5e79bd1a257f462b
