### ISSUE TITLE
Store notes in a channel, instead of a list

### ISSUE THREAD

**Issue by stelar7** [Querijn/BottyMcBotface#174]
This would reduce the spam that botty makes in channels from !notes

messages are linked by `serverid/channelid/messageid`, so it wouldnt be too hard 🤔

**Comment by Querijn** [comment]
As stated before, I'm not too fond of this yet, but it has merit

**Comment by molenzwiebel** [comment]
We can't do this until mobile supports message links, which it doesn't right now.

**Comment by Querijn** [comment]
In that case, I would like to put this on hold.

**Comment by Querijn** [comment]
I'm gonna close this, because it shows that people cannot comprehend they have to click a link or button in the past, which would make linking notes confusing.. I can only imagine how confusing it would be if there was a list of them. It'll have to do for now.
