### ISSUE TITLE
!libs shows "wrong" info

### ISSUE THREAD

**Issue by stelar7** [Querijn/BottyMcBotface#179]
Using `!libs` makes botty say that he has libs for many languages. This should be filtered to only show what languages have up-to-date libraries. (to prevent users seeing the no-libs message)

e.g;
`I have up-to-date libraries for the following languages: java, javascript, php, python`

Maybe also add a subcommand to show all languages, even if they are outdated? or a list to the repo?

**Comment by Querijn** [comment]
Agreed
