### ISSUE TITLE
nextId should be reset to 0 after #office-hours opens

### ISSUE THREAD

**Issue by stelar7** [Querijn/BottyMcBotface#18]
Resetting to 0 is ok because we empty the array. (looks like that was changed in 222d08c8?)
This prevents large UUIDs.
It removes the need for the `nextId` member, and function.
and allows us to use `Math.max() + 1` on the questions to get the next free id.

**Comment by stelar7** [comment]
And to add on that, we can remove nextId from the OfficeHoursData interface, and Math.max the questions.uuid

**Comment by Querijn** [comment]
That reference is incorrect, it should be issue 19.

I don't think this is an issue, the nextId implementation was a bit confusing. If there was no need for an ID, why was there an ID in the object?

Besides that, the ID could have been Array.length

**Comment by stelar7** [comment]
The id is there so we can delete the questions. The details of how its implemented isnt that important, but i feel like we should avoid having 3+ digit ids. 

On a sidenote, where is the questions array emptied? 🤔

**Comment by Querijn** [comment]
The ID will match the array index, so there would be no need to store it.

Just looked at the array, it isn't emptied. I thought I had the line that I removed somewhere else.
