### ISSUE TITLE
Finding a random user with the @everyone role can find users with other roles aswell

### ISSUE THREAD

**Issue by stelar7** [Querijn/BottyMcBotface#19]
Since _everyone_ has the `@everyone` role, getting a random user with that role has a chance to get a guru/rioter aswell, that means the open/closed status for #office-hours will be wrong.

**Comment by Querijn** [comment]
Darn it you're right, this was still on the todo list.

**Comment by stelar7** [comment]
Fixed in 5816ad8695736084a29440fb96744abfadf6b199
