### ISSUE TITLE
New user link filter whitelist

### ISSUE THREAD

**Issue by MingweiSamuel** [Querijn/BottyMcBotface#192]
Feature request - currently botty blocks new users' posts with links and gurus have to approve them manually (afaik). Would be nice to not blacklist certain domains like `*.leagueoflegends.com`, because the link blocking is pretty disruptive to conversations

**Comment by Querijn** [comment]
Makes sense, yes. Don't think bots will be able to avoid good domains.

**Comment by stelar7** [comment]
fixed with https://github.com/Querijn/BottyMcBotface/commit/d5a80a28f6edfcca4e9f1d366030797a726a56b7 ?
