### ISSUE TITLE
When deleting a question, a message is sent regardless whether or not a question has actually been deleted

### ISSUE THREAD

**Issue by stelar7** [Querijn/BottyMcBotface#197]
in here it seems;
https://github.com/Querijn/BottyMcBotface/blob/0f6cd50bee4775dfefe180a064125f1d1ef70cb2/src/OfficeHours.ts#L127-L131

**Comment by Querijn** [comment]
What?

**Comment by stelar7** [comment]
if you do !question remove 32489573495, it still prints the remove message.
