### ISSUE TITLE
Add !answer

### ISSUE THREAD

**Issue by stelar7** [Querijn/BottyMcBotface#200]
Add `!answer` as a component of `!ask`, this way questions can be answered without opening #office-hours

**Comment by Querijn** [comment]
Could be nice, what would be the behaviour of this command?

**Comment by stelar7** [comment]
Ideally, botty would post the answer in the #office-hours channel using webhooks.

ie. someone does `!ask can i hack the game?`
botty would post in #moderators:
```@xysdasda said "can i hack the game?" this question has id X, 
you can use !remove {id} or !answer {id} to deal with it now```

then someone could do `!answer X lolno` and that would make botty post in #office-hours with the name and icon of the one who did the question, aswell as the !answer.

(replace \@whatever with a message)
```
@xysdasda said "can i hack the game? 
@somerioter said "lolno"
```

**Comment by Querijn** [comment]
Sensible. Sounds good.
