### ISSUE TITLE
GArena note changes

### ISSUE THREAD

**Issue by RayZz-** [Querijn/BottyMcBotface#220]
As the announcement has stated by gene in an announcement the api will be deprecated (December 6th) so botty's message should be updated to match it.

**Comment by Querijn** [comment]
The welcome message is still wrong, right?

**Comment by RayZz-** [comment]
I'm not quite sure what your referring to since this was for the issue was for the garena changes.

**Comment by Querijn** [comment]
Never mind, thought there was another one in the welcome message.

**Comment by RayZz-** [comment]
That is correct there is no message regarding the garena server in botty's welcome message
