### ISSUE TITLE
Finish command manager.

### ISSUE THREAD

**Issue by Querijn** [Querijn/BottyMcBotface#48]
- [ ] Make commands toggable.
- [ ] Separate commands per handler.
- [ ] Test

**Comment by stelar7** [comment]
I've got this working on the [command branch](https://github.com/stelar7/BottyMcBotface/tree/commands) now, with the caveat that all command functions must be called with the arrow syntax as seen [here](https://github.com/stelar7/BottyMcBotface/blob/commands/src/CommandController.ts#L72), not sure if you still wanna do it yourself or pull the branch for tests?

**Comment by stelar7** [comment]
This can be closed?
