### ISSUE TITLE
Users aren't being messaged at the opening of office-hours.

### ISSUE THREAD

**Issue by Querijn** [Querijn/BottyMcBotface#49]
Might be a silent fail, might be something being overlooked. No error messages, unfortunately.

**Comment by stelar7** [comment]
This works fine, just tested it. Tho there might be an issue fetching the latest if botty restarts.

**Comment by Querijn** [comment]
That is a separate issue, but I'll get on it

**Comment by stelar7** [comment]
Doing !close, !open, !close to reset the messageId makes mention tagging work fine?

**Comment by Querijn** [comment]
No using !open and !close in a different server.

Using !open and !close on live should reset the messageId.

**Comment by Querijn** [comment]
Issue was that the users required to be fetched. This was a separate call. The users were present if the message was seen while online.
