### ISSUE TITLE
findKey regex does not match keys that do not begin with RGAPI

### ISSUE THREAD

**Issue by stelar7** [Querijn/BottyMcBotface#6]
Some keys (mostly prod keys i guess) do not start with RGAPI.

**Comment by molenzwiebel** [comment]
With the move to v3, all old keys have been reset. Even production keys that hadn't been regenerated in a certain timeframe have been reset. As such, any key that still exists without RGAPI is surely invalid.

**Comment by stelar7** [comment]
This is false, as my production key atm does not contain RGAPI

**Comment by Derpthemeus** [comment]
I can confirm that there are indeed some active keys which are not prefixed with `RGAPI-`

**Comment by Querijn** [comment]
This was indeed apparently a wrong assumption on my part. I removed this because of the fact that some urls that are not riot api urls contain UUIDs for whatever reason. This procs the keyfinder and messages moderators incorrectly with a 'dead key' message.

Need to somehow differentiate checking inside URLS, to make sure it's a riot api dev url.

**Comment by stelar7** [comment]
`if url.startsWith('.*?api.riotgames.com')` or something

**Comment by Querijn** [comment]
Thing is, the whole message body is passed into the checker. We could eat up anything before the UUID and see if it matches a url.

**Comment by Derpthemeus** [comment]
We should check for an API URL before and after the UUID - the message could be a code snippet where the key is defined as a variable before the API call URL, or a plain URL where the key is after the URL.
Maybe check all UUIDs that begin with `RGAPI-`, and also check any UUIDs in messages that contain `api.riotgames.com`?

**Comment by UghThatGuyAgain** [comment]
Are all keys 42 characters long? This includes the hyphens inside as well. It might be inefficient, but you can find where "key=" is put in the URL, and then slice off the key. 

Though I also missed context and could just be talking crazy 😄

**Comment by Derpthemeus** [comment]
Keys are either in the format `RGAPI-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx` or `xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx`, where `x` is a hexadecimal digit. Also, the key won't always be a constant in the URL - they could be stored in a variable.

**Comment by Querijn** [comment]
We could also fix it by just not posting inactive keys to the chat.

**Comment by UghThatGuyAgain** [comment]
If the key is stored in a variable, then it isn’t being exposed and we shouldnt need to worry about it, correct?

**Comment by Derpthemeus** [comment]
> pls halp, this no work
> ```
> String API_KEY = "RGAPI-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx";
> makeApiRequest("https://na1.api.riotgames.com/lol/summoner/v3/summoners/by-name/Derpthemeus?api_key=" + API_KEY);
> ```

**Comment by WxWatch** [comment]
Might just have to have botty do the lifting and just check against the API. If it isn't a valid key, then don't bother doing anything about it.
