### ISSUE TITLE
Botty reacts to messages that include 'hi' and ends with a dot

### ISSUE THREAD

**Issue by petter-kaspersen** [Querijn/BottyMcBotface#61]
When you type any word that contains "hi" and ends the sentence/word with a dot, botty reacts as if you wrote "hi".

Eg:
`His legacy lives on`  = no reaction, as expected
`His legacy lives on.` = `:waveBoye:` reaction.

**Comment by Querijn** [comment]
Confirmed

**Comment by Querijn** [comment]
Issue is that line https://github.com/Querijn/BottyMcBotface/blob/master/src/AutoReact.ts#L147 used to point to the character after the greeting (which would be `s` in this case), but now works if the end character is in the sentence at all, regardless of position

**Comment by petter-kaspersen** [comment]
Can deploy a fix for it later today, if you're not doing it @Querijn.

**Comment by Querijn** [comment]
I'll leave it in your capable hands :)

**Comment by stelar7** [comment]
closed with 7ac263ced7487872681bd25b3f488ed3231b1af6?

**Comment by Querijn** [comment]
yes thanks
