### ISSUE TITLE
Simplify linking to API endpoints

### ISSUE THREAD

**Issue by TiFu** [Querijn/BottyMcBotface#76]
Currently linking to API endpoints like `match` or `summoner` requires going to the dev portal and copy pasting the link to it. 
I'd like to add a new command `!endpoint summoner|match|....` which automatically posts the link to the endpoint.

One could also think about trying to automatically detect sentences like `use the summoner endpoint` and then automatically send a link to it. This feature would need a cooldown though to avoid spamming the chat.

Which version should be implemented?

I'll start working on the basic structure today and then adapt it depending on the chosen version.

**Comment by Querijn** [comment]
Rate limiting should be its own feature inside the command handler possibly. Endpoint command seems like a good idea! Potentially built on the riot api schema? 

https://github.com/Querijn/BottyMcBotface/blob/API-URL-Fetch/src/ApiUrlInterpreter.ts#L384

**Comment by TiFu** [comment]
Sounds good. Thanks for the input!
