### ISSUE TITLE
Rewrite Bot & Merge Heim

### ISSUE THREAD

**Issue by Azoy** [Querijn/BottyMcBotface#8]
This is a discussion to see the thoughts on rewriting botty. The main argument right now is that some don’t know typescript preventing contributions from users. If we wrote it in JS or python I feel there would be a larger contribution base. I also want to discuss ideas of merging Botty and Heimerdinger.

**Comment by Querijn** [comment]
I'm all for the merge, but my preference is with Typescript

**Comment by Querijn** [comment]
For the record, Molen agreed. Will put it in a branch!

**Comment by TiFu** [comment]
Alright. I'll try to port the api status in the upcoming days. Probably on my flight to China.

**Comment by Querijn** [comment]
The API status was ported, and is on the master branch. 

The API url reader is on the APIUrlInterpreter branch, and it would be cool if someone could check it out :)

**Comment by TiFu** [comment]
Are you sure that you pushed the branch? I only see `API-URL-FETCH`.

**Comment by Querijn** [comment]
Yeah, that one. Sorry
