### ISSUE TITLE
Botty's URL rule doesn't listen to commas as endings

### ISSUE THREAD

**Issue by Querijn** [Querijn/BottyMcBotface#91]
Search for: 

"hi im getting an error for matchlist, i respect the params of the request but im getting a 400 status code, here is the request" in #riot-api

![image](https://user-images.githubusercontent.com/3397066/41367831-7a8fc4ba-6f40-11e8-890f-652f61d1819e.png)

**Comment by stelar7** [comment]
This seems to have been fixed by Derps' rewrite.
